---
version: "3.9"
services:
  mobileapp:
    volumes:
      - nmis-mobile-sync:/app/node_modules:nocopy
  backend:
    image: nginx:1.25.1-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend/json:/usr/share/nginx/html:delegated
      - ./backend/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  nmis-mobile-sync:
    external: true
