---
version: "3.9"
services:
  mobileapp:
    image: node:18.16.0-alpine
    command: ["./start.sh"]
    volumes:
      - ./app:/app:delegated
    working_dir: /app
    ports:
      - 8081:8081
      - 19000:19000
