---
version: "3.9"
services:
  mobileapp:
    environment:
      - BACKEND_IP_ADDRESS=${IP_ADDRESS}
    volumes:
      - nmis-mobile-sync:/app/node_modules:nocopy
      - ./.git:/app/.git:ro
  backend:
    image: nginx:1.25.1-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend/json:/var/www/html
      - ./backend/sqlite:/var/www/html/sqlite
      - ./backend/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - api-network
  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./backend/php:/var/www/html
      - ./backend/json:/var/www/html/json:ro
    networks:
      - api-network
volumes:
  nmis-mobile-sync:
    external: true
networks:
  api-network:
    driver: bridge
