export const config = [
  {
    id: 1,
    name: 'Server',
    description: 'URL, Username, Password',
    fields: [
      {
        id: 11,
        type: 'text',
        label: 'Server URL',
        name: 'serverUrl',
        description: null,
        key: 'AuthStore.serverUrl',
      },
      {
        id: 12,
        type: 'text',
        name: 'username',
        label: 'Username',
        description: null,
        key: 'AuthStore.username',
      },
      {
        id: 13,
        type: 'password',
        name: 'password',
        label: 'Password',
        description: null,
        key: 'AuthStore.password',
      },
      {
        id: 4,
        type: 'switch',
        name: 'authenticationCode',
        label: 'Auth Code',
        description: 'Using authentication code',
        key: 'AuthStore.authenticationCode',
      },
    ],
  },
  {
    id: 2,
    name: 'User Interface',
    description: 'App Language, Theme, Font-size',
    fields: [
      {
        id: 21,
        type: 'text',
        name: 'lang',
        label: 'Language',
        description: 'Application language',
        key: 'UIStore.lang',
      },
      {
        id: 22,
        type: 'switch',
        name: 'isDarkMode',
        label: 'Dark mode',
        description: 'Switch theme to dark mode',
        key: 'UIStore.isDarkMode',
      },
      {
        id: 23,
        type: 'slider',
        name: 'fontSize',
        label: 'Font size',
        description: null,
        key: 'UIStore.fontSize',
        slider: {
          min: 0,
          max: 12,
          step: 4,
        },
      },
    ],
  },
  {
    id: 3,
    name: 'Form Management',
    description: 'Sync interval, Sync method',
    fields: [
      {
        id: 31,
        type: 'number',
        name: 'syncInterval',
        label: 'Sync interval',
        description: 'Sync interval in minutes',
        key: 'UserStore.preferences',
      },
      {
        id: 32,
        type: 'switch',
        label: 'Sync Wifi',
        name: 'syncWifiOnly',
        description: 'Sync Wifi only',
        key: 'UserStore.preferences',
      },
    ],
  },
];
