export const config = [
  {
    id: 1,
    name: 'Server',
    description: 'URL, Username, Password',
    fields: [
      {
        id: 11,
        type: 'text',
        label: 'Server URL',
        name: 'serverURL',
        description: null,
        key: 'BuildParamsState.serverURL',
        editable: false,
      },
      {
        id: 14,
        type: 'text',
        name: 'authenticationCode',
        label: 'Auth Code',
        description: null,
        key: 'AuthState.authenticationCode',
        editable: false,
      },
      {
        id: 31,
        type: 'number',
        name: 'syncInterval',
        label: 'Sync interval',
        description: 'Sync interval in minutes',
        key: 'UserState.syncInterval',
        editable: true,
      },
      {
        id: 32,
        type: 'switch',
        label: 'Sync Wifi',
        name: 'syncWifiOnly',
        description: 'Sync Wifi only',
        key: 'UserState.syncWifiOnly',
        editable: true,
      },
    ],
  },
  {
    id: 2,
    name: 'User Interface',
    description: 'App Language, Theme, Font-size',
    fields: [
      {
        id: 21,
        type: 'dropdown',
        name: 'lang',
        label: 'Language',
        description: 'Application language',
        key: 'UIState.lang',
        editable: true,
        options: [
          {
            label: 'English',
            value: 'en',
          },
          {
            label: 'French',
            value: 'fr',
          },
        ],
      },
      {
        id: 22,
        type: 'switch',
        name: 'isDarkMode',
        label: 'Dark mode',
        description: 'Switch theme to dark mode',
        key: 'UIState.isDarkMode',
        editable: true,
      },
      {
        id: 23,
        type: 'slider',
        name: 'fontSize',
        label: 'Font size',
        description: null,
        key: 'UIState.fontSize',
        editable: true,
        slider: {
          minimumValue: 12,
          maximumValue: 24,
          step: 4,
        },
      },
    ],
  },
];
